"""2nd migration

Revision ID: 70b4691dcae9
Revises: b8c3caf512e8
Create Date: 2024-07-04 18:57:56.285323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b4691dcae9'
down_revision = 'b8c3caf512e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###
